Repository LandvibeDev/web-chat-backend, pull requests merged in 2020-08, with the labels that each got.

#8 Message Type 임시 데이터 대문자로 변경
  src/main/resources/data.sql
Labels: fix

#9 채팅방 입장시 메시지 리스트 조회하는 기능 추가
  build.gradle
  src/main/java/web/chat/backend/controller/RoomController.java
  src/main/java/web/chat/backend/controller/response/MessageResponse.java
  src/main/java/web/chat/backend/controller/response/collector/MessageCollector.java
  src/main/java/web/chat/backend/entity/Message.java
  src/main/java/web/chat/backend/exception/NotFoundException.java
  src/main/java/web/chat/backend/repository/MessageRepository.java
  src/main/java/web/chat/backend/service/MessageService.java
  src/main/resources/data.sql
  src/test/java/web/chat/backend/ChatApplicationTest.java
  src/test/java/web/chat/backend/controller/RoomControllerTest.java
  src/test/resources/application.yml
  src/test/resources/test-sql/messages.sql
Labels: feature

#11 Message -> MessageResponse 변형 작업 수정
  src/main/java/web/chat/backend/controller/RoomController.java
  src/main/java/web/chat/backend/controller/response/MessageResponse.java
  src/main/java/web/chat/backend/controller/response/collector/MessageCollector.java
  src/main/java/web/chat/backend/service/MessageService.java
Labels: fix

#14 AWS ECS 배포 설정 추가
  .github/workflows/nginx.yml
  .github/workflows/webchat.yml
  Dockerfile
  nginx/Dockerfile
  nginx/mime.types
  nginx/nginx.conf
  nginx/task-definition.json
  src/main/java/web/chat/backend/controller/HealthController.java
  src/main/resources/application-dev.yml
  task-definition.json
Labels: feature

#18 채팅방 조회/생성 관련 테스트케이스 템플릿 추가
  src/main/java/web/chat/backend/ChatApplication.java
  src/main/java/web/chat/backend/config/JpaConfig.java
  src/main/java/web/chat/backend/controller/ExceptionController.java
  src/main/java/web/chat/backend/entity/Message.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/test/java/web/chat/backend/controller/RoomControllerIntegrationTest.java
  src/test/java/web/chat/backend/controller/RoomControllerTest.java
  src/test/resources/application.yml
Labels: feature, fix

#17 Fix/deployment
  .github/workflows/nginx.yml
  .github/workflows/webchat.yml
  nginx/Dockerfile
  nginx/mime.types
  nginx/nginx.conf
Labels: fix

#23 채팅방 목록 내려주는 api 관련 tc 추가 (#20)
  apps/h2db/crm
  src/main/java/web/chat/backend/entity/Room.java
  src/test/java/web/chat/backend/controller/RoomControllerIntegrationTest.java
  src/test/java/web/chat/backend/controller/RoomControllerTest.java
  src/test/resources/application.yml
Labels: feature

#22 채팅방 생성 api 관련 tc 추가 (#21)
  src/main/java/web/chat/backend/entity/Room.java
  src/test/java/web/chat/backend/controller/RoomControllerIntegrationTest.java
  src/test/java/web/chat/backend/controller/RoomControllerTest.java
Labels: feature

#24 메시지 전송 api 구현
  src/main/java/web/chat/backend/controller/RoomController.java
  src/main/java/web/chat/backend/controller/request/MessageRequest.java
  src/main/java/web/chat/backend/entity/Message.java
  src/main/java/web/chat/backend/entity/Room.java
  src/main/java/web/chat/backend/service/MessageService.java
  src/main/java/web/chat/backend/service/RoomService.java
  src/test/java/web/chat/backend/controller/MessageCreationTest.java
  src/test/java/web/chat/backend/controller/RoomControllerTest.java
  src/test/java/web/chat/backend/repository/MessageRepositoryTest.java
Labels: feature, fix

#27 메시지 조회 기능에 대한 tc 추가
  apps/h2db/crm
  src/test/java/web/chat/backend/repository/MessageRepositoryTest.java
  src/test/java/web/chat/backend/service/MessageServiceTest.java
Labels: feature

#29 채팅방 입장시 메시지가 없으면 에러 발생
  src/main/java/web/chat/backend/controller/RoomController.java
  src/main/java/web/chat/backend/controller/response/MessagesResponse.java
  src/main/java/web/chat/backend/controller/response/collector/MessageCollector.java
  src/main/java/web/chat/backend/service/MessageService.java
  src/test/java/web/chat/backend/controller/RoomControllerIntegrationTest.java
  src/test/java/web/chat/backend/controller/RoomControllerTest.java
  src/test/java/web/chat/backend/service/MessageServiceTest.java
Labels: enhancement, fix

#33 잘못된 경로로 접근한 경우, 디폴트 페이지로 이동할 수 있도록 nginx 설정 추가
  nginx/Dockerfile
  nginx/nginx.conf
Labels: enhancement
